export default function Home() {
	return (
		<div>
			<h1 className='text-4xl font-bold'>Welcome to LunaJs</h1>
			<p className='text-lg'>
                Generated by create next app
			</p>
		</div>
	);
}
